defaults:
  - _self_
  - training: sleeper
  - training/experiment@training.sleeper_experiment: sleeper_topk_r64_k8
  - lr_scheduler: cosine
  - logger: wandb
  # - override hydra/launcher: submitit_slurm
seed: 42
experiment_name: ${training.method}_${now:%Y%m%d_%H%M%S}
